# Beta-Lactam Knowledge Graph Configuration
paths:
  drugbank_xml: data/drugbank/full-database.xml
  kg_dir: data/kg
  results_dir: results
  cache_dir: .cache

train:
  model: mini_transe
  dim: 128
  epochs: 100
  lr: 0.001
  batch_size: 1024

eval:
  k_list: [1, 3, 10]
  negatives_per_pos: 1

validation:
  top_k: 100
  europe_pmc_page_size: 25
  rate_limit_s: 0.5

organism:
  string_species_id: 511145  # E. coli K-12

# Data Sources
data_sources:
  drugbank: data/drugbank_edges.tsv
  string: data/string_interactions.tsv
  chembl: data/chembl_targets.tsv
  drugcomb: data/kg/drugcomb_edges.tsv
  card: data/kg/card_edges.tsv

# Output Paths
outputs:
  model_dir: results/trained_model/
  metrics: results/metrics.json
  predictions: results/predicted_links.tsv
  validation:
    europe_pmc: results/validation/epmc_hits.tsv
    drugcomb: results/validation/drugcomb_hits.tsv
    summary: results/validation/validation_summary.tsv

# Logging
logging:
  level: INFO
  file: logs/pipeline.log
